version: "3.9"

services:
  front:
    image: zcorp0902746/wheelz-front-service:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.labels.node-role == apps
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.wheelz-front-service.rule=Host(`wheelz-front.zcorp.ovh`)
        - traefik.http.routers.wheelz-front-service.entrypoints=websecure
        - traefik.http.routers.wheelz-front-service.tls.certresolver=myresolver
        - traefik.http.services.wheelz-front-service.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
