version: "3.9"

services:
  chain:
    image: zcorp0902746/wheelz-chain-service:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == apps
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.wheelz-chain-service.rule=Host(`wheelz-chain.zcorp.ovh`)
        - traefik.http.routers.wheelz-chain-service.entrypoints=websecure
        - traefik.http.routers.wheelz-chain-service.tls.certresolver=myresolver
        - traefik.http.services.wheelz-chain-service.loadbalancer.server.port=3000
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 3000
      TRANSACTION_QUEUE_URL: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      TRANSACTION_QUEUE_NEW_NAME: transactions_new
      TRANSACTION_QUEUE_COMPLETED_NAME: transactions_completed
      DATA_SIGNER_ALGORITHM: ${SIGNATURE_ALGORITHM}
      DATA_SIGNER_PUBLIC: ${SIGNATURE_PUBLIC}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CHAIN_STATE_DB_NAME: chain_state_service_db
      CHAIN_STATE_DB_USERNAME: ${POSTGRES_USER}
      CHAIN_STATE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      CHAIN_STATE_DB_HOST: postgres
      CHAIN_STATE_DB_PORT: 5432
      TRANSACTION_SERVICE_URL: http://transaction:3000
      USER_SERVICE_URL: http://user:3000
      AUTH_SERVICE_URL: http://auth:3000
      CHAIN_URI: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017
      CHAIN_DATABASE_NAME: ${MONGODB_DATABASE}
      CHAIN_COLLECTION_NAME: blocks
      LOG_LEVEL: info
    networks:
      - proxy
      - database
networks:
  proxy:
    external: true
  database:
    external: true
