version: "3.9"

services:
  kerek:
    image: zcorp0902746/wheelz-kerek-service:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == apps
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.wheelz-kerek-service.rule=Host(`wheelz-kerek.zcorp.ovh`)
        - traefik.http.routers.wheelz-kerek-service.entrypoints=websecure
        - traefik.http.routers.wheelz-kerek-service.tls.certresolver=myresolver
        - traefik.http.services.wheelz-kerek-service.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
