version: "3.9"

services:
  goblin:
    image: zcorp0902746/wheelz-goblin-service:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == apps
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.wheelz-goblin-service.rule=Host(`wheelz-goblin.zcorp.ovh`)
        - traefik.http.routers.wheelz-goblin-service.entrypoints=websecure
        - traefik.http.routers.wheelz-goblin-service.tls.certresolver=myresolver
        - traefik.http.services.wheelz-goblin-service.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
