---
- name: "Validate stack name is defined"
  ansible.builtin.fail:
    msg: "stack_deploy_name must be defined"
  when: stack_deploy_name == ""

- name: "Validate compose files are provided"
  ansible.builtin.fail:
    msg: "stack_deploy_compose_files must contain at least one file"
  when: stack_deploy_compose_files | length == 0

- name: "Create stack directory"
  ansible.builtin.file:
    path: "{{ stack_deploy_dir }}/{{ stack_deploy_name }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: "Copy compose files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ stack_deploy_dir }}/{{ stack_deploy_name }}/{{ item | basename }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop: "{{ stack_deploy_compose_files }}"
  when: stack_deploy_action != "remove"

- name: "Deploy Docker stack"
  community.docker.docker_stack:
    name: "{{ stack_deploy_name }}"
    compose: "{{ stack_deploy_dir }}/{{ stack_deploy_name }}/{{ item | basename }}"
    state: present
    resolve_image: "{{ stack_deploy_resolve_image | default('never') }}"
    prune: "{{ stack_deploy_prune | default(false) }}"
    with_registry_auth: "{{ stack_deploy_with_registry_auth | default(false) }}"
  loop: "{{ stack_deploy_compose_files }}"
  environment: "{{ stack_deploy_env_vars | default({}) }}"
  when: stack_deploy_action == "deploy"
  no_log: true

- name: "Update Docker stack"
  community.docker.docker_stack:
    name: "{{ stack_deploy_name }}"
    compose: "{{ stack_deploy_dir }}/{{ stack_deploy_name }}/{{ item | basename }}"
    state: present
    resolve_image: "always"
    prune: "{{ stack_deploy_prune | default(false) }}"
    with_registry_auth: "{{ stack_deploy_with_registry_auth | default(false) }}"
  loop: "{{ stack_deploy_compose_files }}"
  environment: "{{ stack_deploy_env_vars | default({}) }}"
  when: stack_deploy_action == "update"
  no_log: true

- name: "Remove Docker stack"
  community.docker.docker_stack:
    name: "{{ stack_deploy_name }}"
    state: absent
  retries: "{{ stack_deploy_absent_retries | default(3) }}"
  delay: "{{ stack_deploy_absent_delay | default(10) }}"
  when: stack_deploy_action == "remove"

- name: "Clean files after stack removal"
  ansible.builtin.file:
    path: "{{ stack_deploy_dir }}/{{ stack_deploy_name }}"
    state: absent
  when: stack_deploy_action == "remove"
