version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
    networks:
      - proxy
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      placement:
        constraints: [node.labels.infra == true ]
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true

volumes:
  rabbitmq_data:
