storage:
  type: sqlite
  path: /data/data.db
web:
  port: 8080
metrics: false
debug: false
ui:
  title: Zcorp Health
  header: Zcorp
alerting:
  discord:
    webhook-url: https://discord.com/api/webhooks/1288432327885590608/m5dB8i6PwXaz6DLP77Boj48DPCxjVg3x9G0lOSN1YLiy-Mk1dPtxZ0PdXrPDeeMgfJd1
    default-alert:
      description: "health check failed"
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 5

skip-invalid-config-update: true
