endpoints:
  - name: Check Minio Ui
    group: Minio
    url: "https://minio-ui.zcorp.ovh/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "Minio is down"
