endpoints:
  - name: Check RabbitMq Server
    group: RabbitMq
    url: "tcp://rabbitmq-server.zcorp.ovh:5672"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        description: "RabbitMq Server is down"
  - name: Check RabbitMq Ui
    group: RabbitMq
    url: "https://rabbitmq-ui.zcorp.ovh/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "RabbitMq Ui is down"
