version: "3.8"

services:
  webhook:
    image: zcorp0902746/webhook-service:latest
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.wheelz-auth-service.rule=Host(`webhook.zcorp.ovh`)
        - traefik.http.routers.wheelz-auth-service.entrypoints=websecure
        - traefik.http.routers.wheelz-auth-service.tls.certresolver=myresolver
        - traefik.http.services.wheelz-auth-service.loadbalancer.server.port=3000
    environment:
      HOST: "0.0.0.0"
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    networks:
      - proxy
networks:
  proxy:
    external: true
