apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:xZxCORP/infra.git'
    targetRevision: HEAD
    path: k3s/apps/nginx-site
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
