---
docker_apt_version: 5:28.0.4-1~ubuntu.24.04~noble
docker_gpg_file: "{{ apt_keyrings_dir }}/docker.gpg"
docker_apt_repository: "https://download.docker.com/linux/ubuntu"
docker_gpg_url: "{{ docker_apt_repository }}/gpg"
