---
- name: Install Docker
  ansible.builtin.include_tasks: docker.yml
- name: Setup firewall rules
  ansible.builtin.include_tasks: firewall.yml
  when: docker_swarm_firewall | default(true)
- name: Setup swarm manager
  ansible.builtin.include_tasks: manager.yml
  when: docker_swarm_role == "manager"

- name: Setup swarm worker
  ansible.builtin.include_tasks: worker.yml
  when: docker_swarm_role == "worker"
