- name: Check if Docker networks exist
  community.docker.docker_network_info:
    name: "{{ item.name }}"
  loop: "{{ docker_swarm_networks }}"
  register: docker_swarm_existing_networks
  ignore_errors: true

- name: Create Docker networks for Swarm (only if not existing)
  community.docker.docker_network:
    name: "{{ item.item.name }}"
    driver: "{{ item.item.driver }}"
    attachable: "{{ item.item.attachable | default(omit) }}"
    state: "{{ item.item.state | default('present') }}"
    scope: "{{ 'swarm' if item.item.driver == 'overlay' else omit }}"
  loop: "{{ docker_swarm_existing_networks.results }}"
  when: not item.exists
