---
# tasks file for roles/consul
- name: Install Consul
  ansible.builtin.apt:
    name: consul
    state: present

- name: Create Consul configuration directory
  ansible.builtin.file:
    path: "/etc/consul.d"
    state: directory
    mode: '0755'

- name: Upload Consul configuration file
  ansible.builtin.template:
    src: "consul.hcl.j2"
    dest: "/etc/consul.d/consul.hcl"
    mode: '0644'
- name: Open Consul ports with iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 8300
    - 8301
    - 8302
    - 8500
    - 8600
- name: save current state of the firewall in system file
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4

- name: Enable and start Consul
  ansible.builtin.systemd:
    name: consul
    enabled: yes
    state: started

