version: "3.9"

services:
  loki:
    image: grafana/loki:3.4.5
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == infra
      restart_policy:
        condition: on-failure
    command: -config.file=/etc/loki/local-config.yaml
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
        mode: 0644
    volumes:
      - loki_data:/loki
    networks:
      - monitoring

networks:
  monitoring:
    external: true
volumes:
  loki_data:
configs:
  loki_config:
    file: /opt/config/loki/local-config.yaml
    name: loki_config_v1.0
