version: "3.8"

services:
  backend:
    image: zcorp0902746/techfreedom-backend:latest
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.techfreedom-backend.rule=Host(`techfreedom-backend.zcorp.ovh`)
        - traefik.http.routers.techfreedom-backend.entrypoints=websecure
        - traefik.http.routers.techfreedom-backend.tls.certresolver=myresolver
        - traefik.http.services.techfreedom-backend.loadbalancer.server.port=8090
    environment:
      DefaultConnection: "server=mysql_mysql;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}"

    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8090/testSuccess"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    image: zcorp0902746/techfreedom-frontend:latest
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure

      labels:
        - traefik.enable=true
        - traefik.http.routers.techfreedom-frontend.rule=Host(`techfreedom-frontend.zcorp.ovh`)
        - traefik.http.routers.techfreedom-frontend.entrypoints=websecure
        - traefik.http.routers.techfreedom-frontend.tls.certresolver=myresolver
        - traefik.http.services.techfreedom-frontend.loadbalancer.server.port=80

    networks:
      - proxy

networks:
  proxy:
    external: true
