version: "3.9"
services:
  docmost:
    image: docmost/docmost:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == infra
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.docmost.rule=Host(`docmost.zcorp.ovh`)
        - traefik.http.routers.docmost.entrypoints=websecure
        - traefik.http.routers.docmost.tls.certresolver=myresolver
        - traefik.http.services.docmost.loadbalancer.server.port=3000
    environment:
      APP_URL: "https://docmost.zcorp.ovh"
      APP_SECRET: ${DOCMOST_APP_SECRET}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
      STORAGE_DRIVER: "s3"
      AWS_S3_ACCESS_KEY_ID: ${MINIO_USERNAME}
      AWS_S3_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      AWS_S3_BUCKET: "docmost"
      AWS_S3_ENDPOINT: "https://minio-server.zcorp.ovh"
      AWS_S3_REGION: "us-east-1"
      AWS_S3_FORCE_PATH_STYLE: "true"
      MAIL_DRIVER: "smtp"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      MAIL_FROM_ADDRESS: ${SMTP_USERNAME}
      MAIL_FROM_NAME: "Wheelz"
    volumes:
      - docmost_data:/app/data/storage

    networks:
      - database
      - proxy

volumes:
  docmost_data:
networks:
  database:
    external: true
  proxy:
    external: true
