---
# tasks file for roles/traefik
- name: Ensure stack folder exist
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/stacks_files"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'
  become: true
- name: Ensure traefik folder exist
  ansible.builtin.file:
    path: "/etc/traefik"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'
  become: true
- name: Déployer Traefik avec Docker Compose
  ansible.builtin.template:
    src: traefik-compose.yml.j2
    dest: "/home/{{ansible_user}}/stacks_files/traefik-compose.yml"
  become: true
- name: Synchronize config file
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/roles/traefik/files/traefik.yml"
    dest: "/etc/traefik/traefik.yml"
    mode: push
    delete: false
  become: true
- name: Deploy traefik stack
  community.docker.docker_stack:
    state: present
    name: traefik
    prune: true
    compose:
      - "/home/{{ansible_user}}/stacks_files/traefik-compose.yml"