---
# tasks file for roles/traefik
- name: Create Traefik configuration directory
  file:
    path: /opt/traefik
    state: directory
    mode: '0755'

- name: Copy Traefik configuration
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml

- name: Copy dynamic configuration
  template:
    src: dynamic_conf.yml.j2
    dest: /opt/traefik/dynamic_conf.yml

- name: Copy Docker Compose file
  template:
    src: traefik-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml

- name: Create letsencrypt volume directory
  file:
    path: /opt/traefik/letsencrypt
    state: directory
    mode: '0755'

- name: Start Traefik container
  command: docker compose up -d
  args:
    chdir: /opt/traefik