---

- name: Ensure stack folder exist
  ansible.builtin.file:
    path: "/home/{{ansible_user}}/stacks_files"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'
  become: true
- name: Synchronize compose file
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/roles/techfreedom/files/techfreedom-compose.yml"
    dest: "/home/{{ansible_user}}/stacks_files/techfreedom-compose.yml"
    mode: push
    delete: false
  become: true
- name: Deploy techfreedom stack
  community.docker.docker_stack:
    state: present
    name: techfreedom
    prune: true
    compose:
      - "/home/{{ansible_user}}/stacks_files/techfreedom-compose.yml"

