---
# tasks file for roles/swarm
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Allow manager node communication on port 2377
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 2377
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow Docker Swarm manager communication"
  become: true

- name: Allow overlay network discovery on port 7946 (TCP)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 7946
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow Docker Swarm overlay network discovery (TCP)"
  become: true

- name: Allow overlay network discovery on port 7946 (UDP)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 7946
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow Docker Swarm overlay network discovery (UDP)"
  become: true

- name: Allow overlay network traffic on port 4789 (UDP)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 4789
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow Docker Swarm overlay network traffic"
  become: true
- name: Persist iptables rules
  ansible.builtin.command:
    cmd: netfilter-persistent save
  become: true
- name: Check/init swarm
  docker_swarm:
    state: present
  register: __output_swarm
  when: inventory_hostname in groups['masters'][0]
- name: Create a network
  docker_network:
    name: z_public
    driver: overlay
  when: inventory_hostname in groups['masters'][0]

- name: Install nodes
  docker_swarm:
    state: join
    timeout: 60
    join_token: "{{ hostvars[groups['masters'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Manager'] }}"
    remote_addrs: "{{ groups['masters'][0] }}"
  when: inventory_hostname in groups['masters'] and inventory_hostname not in groups['masters'][0]

- name: Install workers
  docker_swarm:
    state: join
    timeout: 60
    join_token: "{{ hostvars[groups['masters'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ groups['masters'][0] }}"
  when: inventory_hostname in groups['workers']