---
- name: Install required packages
  ansible.builtin.package:
    name:
      - curl
      - iptables
    state: present
  become: true

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true
  become: true
- name: Flush NAT table rules
  ansible.builtin.iptables:
    table: nat
    flush: yes

- name: Flush Mangle table rules
  ansible.builtin.iptables:
    table: mangle
    flush: yes

- name: Flush filter table rules
  ansible.builtin.iptables:
    flush: yes
- name: Allow all incoming, outgoing, and forwarding traffic
  ansible.builtin.iptables:
    chain: INPUT
    policy: ACCEPT

- name: Allow all outgoing traffic
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT

- name: Allow all forwarding traffic
  ansible.builtin.iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  become: true