---
- name: Check if k3s_node_type is defined
  ansible.builtin.fail:
    msg: "k3s_node_type is not 'master' or 'worker'"
  when: k3s_node_type not in ['master', 'worker']

- name: Start common tasks
  ansible.builtin.include_tasks:
    file: common.yml

- name: Start tasks for {{ k3s_node_type }}
  ansible.builtin.include_tasks:
    file: "{{ k3s_node_type }}.yml"
