---
- name: Check if server URL is defined
  ansible.builtin.fail:
    msg: "k3s_server_url is required for worker nodes"
  when: k3s_server_url == ""

- name: Check if node token is defined
  ansible.builtin.fail:
    msg: "k3s_node_token is required for worker nodes"
  when: k3s_node_token == ""

- name: Check if K3s agent is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary
  become: true

- name: Ensure master host has correct protocol
  ansible.builtin.set_fact:
    k3s_master_url: "https://{{ k3s_server_url | regex_replace('^https?://', '') }}:6443"

- name: Install K3s agent directly
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    K3S_URL={{ k3s_master_url }} \
    K3S_TOKEN={{ k3s_node_token }} \
    sh -
  args:
    creates: /usr/local/bin/k3s
  become: true
  register: k3s_agent_install
  when: not k3s_binary.stat.exists