version: '3.8'

services:
  whoami:
    image: "traefik/whoami"
    container_name: whoami
    networks:
      - z_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=z_public"
        - "traefik.http.routers.whoami.rule=Host(`whoami.zcorp.ovh`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"


networks:
  z_public:
    driver: overlay
    attachable: true