version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    deploy:
      placement:
        constraints: [node.labels.infra == true ]
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mysql.entrypoints=mysql"
        - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  mysql_data:
