version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    ports:
      - "3306:3306"
    deploy:
      placement:
        constraints: [node.labels.infra == true ]

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  mysql_data:
