---
# tasks file for roles/portainer
- name: Ensure stack folder exist
  ansible.builtin.file:
    path: "/home/{{ansible_user}}/stacks_files"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'
  become: true
- name: Install jsondiff
  ansible.builtin.pip:
    name: jsondiff
    state: present
- name: Synchronize compose file
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/roles/portainer/files/portainer-compose.yml"
    dest: "/home/{{ansible_user}}/stacks_files/portainer-compose.yml"
    mode: push
    delete: false
  become: true
- name: Deploy Portainer stack
  community.docker.docker_stack:
    state: present
    name: portainer
    compose:
      - "/home/{{ansible_user}}/stacks_files/portainer-compose.yml"

