version: "3.8"

services:
  mongo:
    image: "mongo:latest"
    deploy:
      placement:
        constraints: [node.labels.infra == true ]
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.mongodb.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mongodb.entrypoints=mongodb"
        - "traefik.tcp.services.mongodb.loadbalancer.server.port=27017"
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=root"
      - "MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_USER=${MONGODB_USER}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
    volumes:
      - "mongodb_data:/data/db"
      - ~/configs/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

    networks:
      - proxy

networks:
  proxy:
    external: true


volumes:
  mongodb_data: