version: "3.8"

services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints: [node.labels.infra == true ]
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=root"
      - "MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_USER=${MONGODB_USER}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
    volumes:
      - "mongodb_data:/data/db"
      - ~/configs/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - proxy

networks:
  proxy:
    external: true


volumes:
  mongodb_data: