---
# tasks file for roles/nomad
- name: Install Nomad
  ansible.builtin.apt:
    name: nomad
    state: present

- name: Create Nomad configuration directory
  ansible.builtin.file:
    path: /etc/nomad.d
    state: directory
    mode: '0755'

- name: Deploy Nomad configuration
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    mode: '0644'
- name: Open Consul ports with iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 4646
    - 4647
    - 4648

- name: save current state of the firewall in system file
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4

- name: Start Nomad service
  ansible.builtin.service:
    name: nomad
    enabled: yes
    state: started
- include_tasks: configure_acl.yml
  when: nomad_server