version: "3.8"
services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.labels.infra == true ]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  postgres_data: