---
# tasks file for roles/docker
- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Set up the stable repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker
    - python3-pip
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: ubuntu
    group: docker
  become: true

- name: Ensure Docker is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true