- name: Configure masters nodes
  hosts: masters
  become: true
  roles:
    - role: docker
      tags: docker
    - role: hashicorp_repo
      tags: repo
    - role: consul
      tags: consul
      consul_server: true
    - role: traefik
      tags: traefik

    # - role: nomad
    #   nomad_server: true

- name: Configure workers nodes
  hosts: workers
  become: true
  roles:
    - role: docker
      tags: docker
    - role: consul
      tags: consul
      consul_server: false
    # - role: nomad
    #   nomad_server: false
