---
- name: Install and configure github runners
  hosts:
    - runner
  roles:
    - role: github_runner
      vars:
        github_runner_api_token: "{{ github_api_token }}"
        github_runner_organization: "xZxCORP"
        github_runner_data:
          - name: "runner1"
            labels: ["ubuntu-latest"]
            user: "github-runner"
            dir: "/opt/github-runner/runner1"
            architecture: "arm64"
          - name: "runner2"
            labels: ["ubuntu-latest"]
            user: "github-runner"
            dir: "/opt/github-runner/runner2"
            architecture: "arm64"
  become: true
  tags:
    - ci
