---
- name: Deploy general services
  hosts: master[0]
  become: true
  tasks:
    - name: Deploy Traefik
      ansible.builtin.include_role:
        name: stack_deploy
      vars:
        stack_deploy_name: "traefik"
        stack_deploy_compose_files:
          - "stacks/traefik.yml"
        stack_deploy_prune: true
    - name: Deploy Portainer
      ansible.builtin.include_role:
        name: stack_deploy
      vars:
        stack_deploy_name: "portainer"
        stack_deploy_compose_files:
          - "stacks/portainer.yml"
        stack_deploy_prune: true
    - name: Deploy RabbitMQ
      ansible.builtin.include_role:
        name: stack_deploy
      vars:
        stack_deploy_name: "rabbitmq"
        stack_deploy_compose_files:
          - "stacks/rabbitmq.yml"
        stack_deploy_prune: true
        stack_deploy_env_vars:
          RABBITMQ_USERNAME: "{{ rabbitmq_username }}"
          RABBITMQ_PASSWORD: "{{ rabbitmq_password }}"
  tags:
    - general
