---
- name: Deploy K3s master
  hosts: master
  become: true
  roles:
    - role: k3s
      vars:
        k3s_node_type: master
  tags:
    - k3s
- name: Deploy K3s workers
  hosts: worker
  become: true
  roles:
    - role: k3s
      vars:
        k3s_node_type: worker
        k3s_server_url: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
        k3s_node_token: "{{ hostvars[groups['master'][0]]['k3s_node_token'] }}"
  tags:
    - k3s
- name: Install and configure github runners
  hosts:
    - runner
  roles:
    - role: github_runner
      vars:
        github_runner_api_token: "{{ github_api_token }}"
        github_runner_organization: "xZxCORP"
        github_runner_data:
          - name: "runner1"
            labels: ["linux", "arm64"]
            user: "github-runner"
            dir: "/opt/github-runner/runner1"
            architecture: "arm64"
          - name: "runner2"
            labels: ["linux", "arm64"]
            user: "github-runner"
            dir: "/opt/github-runner/runner2"
            architecture: "arm64"
  become: true
  tags:
    - ci
