- name: Configure masters nodes
  hosts: masters
  become: true
  roles:
    - role: docker
    - role: consul
      consul_server: true
    # - role: nomad
    #   nomad_server: true

- name: Configure workers nodes
  hosts: workers
  become: true
  roles:
    - role: docker
    - role: consul
      consul_server: false
    # - role: nomad
    #   nomad_server: false
