---
- name: Install and configure infrastructure
  hosts:
    - master
    - worker
  roles:
    - role: k3s
      vars:
        k3s_node_type: "{{ 'master' if inventory_hostname in groups['master'] else 'worker' }}"
  become: true
