---
- name: Install deps
  ansible.builtin.package:
    name:
      - curl
      - tar
      - unzip
      - jq
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: true

  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ github_runner_docker_gpg_key_url }}"
    state: present
  become: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ github_runner_docker_repository }}"
    state: present
    update_cache: true
  become: true

- name: Install Docker
  ansible.builtin.package:
    name: docker-ce
    state: present
  become: true

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Create github runner user
  ansible.builtin.user:
    name: "{{ github_runner_user }}"
    shell: /bin/bash
    system: true
    createhome: true
  become: true
- name: Setup sudoers for GitHub runner (no password)
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/github-runner
    line: "{{ github_runner_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    mode: "0440"
    create: true
    validate: "visudo -cf %s"
  become: true
- name: Install runner
  ansible.builtin.include_tasks: install_runner.yml
  loop: "{{ github_runner_data }}"
  loop_control:
    loop_var: runner
    index_var: loop_index
