---
- name: Install deps
  ansible.builtin.package:
    name:
      - curl
      - tar
      - unzip
      - jq
      - git
    state: present
    update_cache: true

  become: true

- name: Create github runner user
  ansible.builtin.user:
    name: "{{ github_runner_user }}"
    shell: /bin/bash
    system: true
    createhome: true
  become: true
- name: Setup sudoers for GitHub runner (no password)
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/github-runner
    line: "{{ github_runner_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    mode: "0440"
    create: true
    validate: "visudo -cf %s"
  become: true
- name: Install runner
  ansible.builtin.include_tasks: install_runner.yml
  loop: "{{ github_runner_data }}"
  loop_control:
    loop_var: runner
    index_var: loop_index
