---
consul_version: "1.18.2"
consul_server: false
consul_datacenter: "dc1"
consul_data_dir: "/opt/consul"
consul_log_level: "INFO"
consul_bind_addr: "{{ ansible_default_ipv4.address }}"
consul_bootstrap_expect: 1
consul_ui_enabled: true
consul_retry_join:
  - "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"