version: "3.9"

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://minio-ui.zcorp.ovh

    command: server /data --console-address ":9001"
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio-server.rule=Host(`minio-server.zcorp.ovh`)
        - traefik.http.routers.minio-server.entrypoints=websecure
        - traefik.http.routers.minio-server.tls.certresolver=myresolver
        - traefik.http.routers.minio-server.service=minio-server
        - traefik.http.services.minio-server.loadbalancer.server.port=9000
        - traefik.http.routers.minio-ui.rule=Host(`minio-ui.zcorp.ovh`)
        - traefik.http.routers.minio-ui.entrypoints=websecure
        - traefik.http.routers.minio-ui.tls.certresolver=myresolver
        - traefik.http.routers.minio-ui.service=minio-ui
        - traefik.http.services.minio-ui.loadbalancer.server.port=9001

networks:
  proxy:
    external: true

volumes:
  minio_data:
