endpoints:
  - name: Check Front service
    group: Wheelz
    url: "https://wheelz-front.zcorp.ovh/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "Wheelz Front Service is down"
  - name: Check User Service
    group: Wheelz
    url: "https://wheelz-user.zcorp.ovh/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    alerts:
      - type: discord
        description: "Wheelz User Service is down"
  - name: Check Auth Service
    group: Wheelz
    url: "https://wheelz-auth.zcorp.ovh/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    alerts:
      - type: discord
        description: "Wheelz Auth Service is down"
  - name: Check Transaction Service
    group: Wheelz
    url: "https://wheelz-transaction.zcorp.ovh/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    alerts:
      - type: discord
        description: "Wheelz Transaction Service is down"
  - name: Check Chain Service
    group: Wheelz
    url: "https://wheelz-chain.zcorp.ovh/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    alerts:
      - type: discord
        description: "Wheelz Chain Service is down"
  - name: Check Goblin Service
    group: Wheelz
    url: "https://wheelz-goblin.zcorp.ovh/status"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == 200"
    alerts:
      - type: discord
        description: "Wheelz Goblin Service is down"
  - name: Check Kerek Service
    group: Wheelz
    url: "https://wheelz-kerek.zcorp.ovh/status"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == 200"
    alerts:
      - type: discord
        description: "Wheelz Goblin Service is down"
  - name: Check Upload Service
    group: Wheelz
    url: "https://wheelz-upload.zcorp.ovh/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    alerts:
      - type: discord
        description: "Wheelz Upload Service is down"
