---
- name: Restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
  become: true

- name: Restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
  become: true
