---
- name: Restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
  become: true

- name: Restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
  become: true
- name: Wait for node-token file
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  become: true
