name: Infra
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: Linux
    permissions:
      contents: write
      pull-requests: write
    outputs:
      infrastructure_changed: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Transcrypt
        run: |
          git clone https://github.com/elasticdog/transcrypt.git
          echo "PATH=$(pwd)/transcrypt:$PATH" >> $GITHUB_ENV
      - name: Decrypt with Transcrypt
        run: |
          transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' -y
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate
      - name: Terraform Plan and Check Changes
        id: check_changes
        working-directory: ./terraform
        run: |
          PLAN_OUTPUT=$(terraform plan -var-file=terraform.tfvars -out=tfplan)
          echo "$PLAN_OUTPUT"
          
          # Vérifier si le message "No changes" est présent
          if echo "$PLAN_OUTPUT" | grep -q "Your infrastructure matches the configuration."; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "Aucun changement détecté"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Des changements ont été détectés"
          fi
      
      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_changes.outputs.has_changes == 'true'
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
      
      - name: Generate Ansible Inventory
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_changes.outputs.has_changes == 'true'
        working-directory: ./terraform
        run: |
          mkdir -p ../ansible/inventory
          terraform output -raw ansible_inventory > ../ansible/inventory/hosts
      
      - name: Commit Inventory File
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ansible/inventory/hosts
          git commit -m "Update Ansible inventory [skip ci]" || echo "No changes to commit"
          git push

  lint:
    runs-on: Linux
    needs: terraform
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git safe directory
        run: |
          git config --global --add safe.directory "$(pwd)"
      - name: Create vault password file
        run: |
          echo '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > ./ansible/.vault-pass.txt
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: "./ansible"

  ansible:
    runs-on: Linux
    needs: [terraform, lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout with latest changes
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Pull latest changes
        run: git pull origin main
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Create vault password file
        run: |
          echo '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > ./ansible/.vault-pass.txt
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/gpe-vm
          chmod 600 ~/.ssh/gpe-vm
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |
          if [ "${{ needs.terraform.outputs.infrastructure_changed }}" == "true" ]; then
            echo "L'infrastructure a changé, exécution du playbook Ansible"
          else
            echo "L'infrastructure n'a pas changé, mais exécution du playbook Ansible quand même"
          fi
          ansible-playbook cluster.yml