name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v4
      - name: Configure Git safe directory
        run: |
          git config --global --add safe.directory "$(pwd)"
      - name: Create vault password file
        run: |
          echo '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > ./ansible/.vault-pass.txt
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: "./ansible"