version: "3.9"

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://minio-ui.zcorp.ovh
    command: server /data --console-address ":9001"
    networks:
      - proxy
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio-server.rule=Host(`minio-server.zcorp.ovh`)
        - traefik.http.routers.minio-server.entrypoints=websecure
        - traefik.http.routers.minio-server.tls.certresolver=myresolver
        - traefik.http.routers.minio-server.service=minio-server
        - traefik.http.services.minio-server.loadbalancer.server.port=9000
        - traefik.http.routers.minio-ui.rule=Host(`minio-ui.zcorp.ovh`)
        - traefik.http.routers.minio-ui.entrypoints=websecure
        - traefik.http.routers.minio-ui.tls.certresolver=myresolver
        - traefik.http.routers.minio-ui.service=minio-ui
        - traefik.http.services.minio-ui.loadbalancer.server.port=9001

  minio-init:
    image: alpine:latest
    depends_on:
      - minio
    environment:
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    configs:
      - source: minio_buckets_config
        target: /buckets-config.json
        mode: "0755"
      - source: minio_init_script
        target: /configure-buckets.sh
        mode: "0755"
    networks:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
      restart_policy:
        condition: none
    entrypoint: ["/bin/sh"]
    command: >
      -c "
        echo '🚀 Démarrage de l initialisation MinIO...'
        apk add --no-cache jq curl netcat-openbsd openssl
        echo '🔧 Téléchargement de mc...'
        curl -O https://dl.min.io/client/mc/release/linux-arm64/mc && chmod +x mc && mv mc /usr/local/bin/
        echo '🔧 Attente que MinIO soit complètement démarré...'
        echo '🔧 Exécution du script de configuration...'
        /configure-buckets.sh
      "

configs:
  minio_buckets_config:
    file: /opt/config/minio/buckets-config.json
    name: minio_buckets_config_v1.5
  minio_init_script:
    file: /opt/config/minio/configure-buckets.sh
    name: minio_init_script_v1.5

networks:
  proxy:
    external: true
  database:
    external: true

volumes:
  minio_data:
