version: "3.9"

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://minio-ui.zcorp.ovh
    command: server /data --console-address ":9001"
    networks:
      - proxy
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio-server.rule=Host(`minio-server.zcorp.ovh`)
        - traefik.http.routers.minio-server.entrypoints=websecure
        - traefik.http.routers.minio-server.tls.certresolver=myresolver
        - traefik.http.routers.minio-server.service=minio-server
        - traefik.http.services.minio-server.loadbalancer.server.port=9000
        - traefik.http.routers.minio-ui.rule=Host(`minio-ui.zcorp.ovh`)
        - traefik.http.routers.minio-ui.entrypoints=websecure
        - traefik.http.routers.minio-ui.tls.certresolver=myresolver
        - traefik.http.routers.minio-ui.service=minio-ui
        - traefik.http.services.minio-ui.loadbalancer.server.port=9001

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    networks:
      - database
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...';
      until /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_USERNAME} ${MINIO_PASSWORD}; do 
        echo 'MinIO not ready yet, retrying in 2 seconds...'; 
        sleep 2; 
      done;
      echo 'MinIO is ready, creating bucket...';
      /usr/bin/mc mb myminio/docmost --ignore-existing;
      echo 'Setting bucket policy to download (read-only public access)...';
      /usr/bin/mc anonymous set download myminio/docmost;
      echo 'Bucket docmost created and configured successfully!';
      exit 0;
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

networks:
  proxy:
    external: true
  database:
    external: true

volumes:
  minio_data:
