version: "3.9"

services:
  mongo:
    image: "mongo:latest"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGO_INITDB_DATABASE=${MONGODB_DATABASE}"
      - "MONGODB_USER=${MONGODB_USER}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - database

  mongo-express:
    image: mongo-express:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
      labels:
        - traefik.enable=true
        - traefik.http.routers.mongo-express.rule=Host(`mongo.zcorp.ovh`)
        - traefik.http.routers.mongo-express.tls.certresolver=myresolver
        - traefik.http.services.mongo-express.loadbalancer.server.port=8081

    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_SITE_BASEURL: /
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    networks:
      - proxy
      - database
    depends_on:
      - mongo

networks:
  proxy:
    external: true
  database:
    external: true

volumes:
  mongodb_data:
