version: "3.8"

services:
  mongo:
    image: "mongo:latest"
    ports:
      - "127.0.0.1:27017:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=root"
      - "MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_USER=${MONGODB_USER}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
    volumes:
      - "mongodb_data:/data/db"
      - /opt/config/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - database

networks:
  database:
    external: true
volumes:
  mongodb_data:
