version: "3.9"
services:
  postgres:
    image: postgres:17.5
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:
    external: true

volumes:
  postgres_data:
