version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    networks:
      - proxy
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-role == persistence
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.zcorp.ovh`)"
        - "traefik.http.routers.rabbitmq.entrypoints=websecure"
        - "traefik.http.routers.rabbitmq.tls.certresolver=myresolver"
        - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

networks:
  proxy:
    external: true

volumes:
  rabbitmq_data:
